FROM node:16.16.0-alpine3.15

ENV NODE_ENV=production
EXPOSE 3001

COPY ./backend/dist /code/backend/dist
COPY ./backend/package.json /code/backend/package.json
COPY ./backend/.env /code/backend/.env
COPY ./package.json /code

WORKDIR /code
RUN npm install

WORKDIR /code/backend
CMD [ "node", "./dist/index.js" ]
