version: "3.8"

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080

  database:
    image: postgres:alpine
    container_name: database-dev
    environment:
      POSTGRES_PASSWORD: "dev"
      POSTGRES_USER: "dev"
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data

  backend:
    image: node:16.16.0-alpine3.15
    container_name: backend-dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3001:3001
    volumes:
      - ..:/code
    working_dir: /code/backend
    command: ["npm", "run", "start"]

  frontend:
    image: node:16.16.0-alpine3.15
    container_name: frontend-dev
    environment:
      WATCHPACK_POLLING: "true"
    ports:
      - 3000:3000
    volumes:
      - ..:/code
    working_dir: /code/frontend
    command: ["npm", "run", "start"]

volumes:
  database-data:
    external: true
